import { Layout } from "@/components/Layout";
import { EmailChecker } from "@/components/EmailChecker";
import { BlogPreview } from "@/components/BlogPreview";
import { SubscribeCTA } from "@/components/SubscribeCTA";
import { Shield, Lock, Bell, Search } from "lucide-react";

const features = [
  {
    icon: Search,
    title: "Instant Checks",
    description: "Search billions of breach records in seconds"
  },
  {
    icon: Lock,
    title: "Privacy First",
    description: "We never store or reveal your passwords"
  },
  {
    icon: Bell,
    title: "Real-time Alerts",
    description: "Get notified when new breaches occur"
  },
  {
    icon: Shield,
    title: "AI Analysis",
    description: "Detailed breach reports generated by AI"
  }
];

const Index = () => {
  return (
    <Layout>
      <EmailChecker />

      {/* Features */}
      <section className="py-12 border-y-2 border-foreground">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            {features.map((feature) => (
              <div key={feature.title} className="text-center">
                <div className="inline-flex items-center justify-center w-12 h-12 bg-secondary border-2 border-foreground shadow-xs mb-4">
                  <feature.icon className="h-6 w-6" />
                </div>
                <h3 className="font-bold mb-1">{feature.title}</h3>
                <p className="text-sm text-muted-foreground">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <BlogPreview />
      <SubscribeCTA />
    </Layout>
  );
};

export default Index;
